#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "menu.h"
#include "game/game.h"

void draw_game_menu_2();
void process_deck1();
void process_deck2();
void process_deck3();
void process_deck4();
void process_deck5();
void process_deck6();
void process_deck7();
void process_deck8();
void process_deck9();
void process_deck10();
void process_deck11();
void process_deck12();
void process_deck13();
void process_deck14();
void process_deck15();
void process_deck16();
