#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "menu.h"
#include "game/game.h"

void draw_game_menu_8_2();
void process_deck1_2();
void process_deck2_2();
void process_deck3_2();
void process_deck4_2();
void process_deck5_2();
void process_deck6_2();
void process_deck7_2();
void process_deck8_2();
void process_deck9_2();
void process_deck10_2();
void process_deck11_2();
void process_deck12_2();
void process_deck13_2();
void process_deck14_2();
void process_deck15_2();
void process_deck16_2();
